### ISSUE TITLE
Publicar a versão v0.1 do jogo no GitHub Pages

### ISSUE THREAD

**Issue by IohanReis** [TiO-Games/jogo_web#26]
Publicar o jogo em sua primeira versão experimental v0.1, no GitHub Pages para jogar nas férias de verão :)

**Comment by IohanReis** [comment]
Colocamos no GitHub Pages, mas a gente sempre está atualizando o arquivo lá

**Comment by ghost** [comment]
URL: https://tio-games.github.io/jogo_web/
